doctrine:
    dbal:
        default_connection: mysql
        connections:
            mysql:
                url: '%env(resolve:MYSQL_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            mssql:
                # configure these for your database server
                url: '%env(resolve:MSSQL_DATABASE_URL)%'
                driver: 'pdo_sqlsrv'
                charset: utf8
    orm:
        default_entity_manager: mysql
        entity_managers:
            mysql:
                connection: mysql
                mappings:
                    App\Mysql:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Mysql'
                        prefix: 'App\Entity\Mysql'
                        alias: Mysql
            mssql:
                connection: mssql
                mappings:
                    App\Mssql:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Mssql'
                        prefix: 'App\Entity\Mssql'
                        alias: Mssql

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
